version: "8.8.8"
services:
  web:
    build: .
    container_name: hw12-web-authentication
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Wait until DB healthcheck passes
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - REDIS_URL=${REDIS_URL}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:15
    container_name: hw12-db-authentication
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    # ♦ HEALTHCHECK — required!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hw12-redis-authentication
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

volumes:
  pgdata:
